// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRCvyugjMRANuvRf1A1ZQMLVetVYr13PE',
    appId: '1:604822129198:web:bc9ccde9e6f2bdc02e2dbf',
    messagingSenderId: '604822129198',
    projectId: 'besthotel-ce019',
    authDomain: 'besthotel-ce019.firebaseapp.com',
    storageBucket: 'besthotel-ce019.firebasestorage.app',
    measurementId: 'G-0B4BGSZBG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULGEzA7zUPz5I5utHmP_XANajcOFHkAM',
    appId: '1:604822129198:android:ca2e43eedb00a2912e2dbf',
    messagingSenderId: '604822129198',
    projectId: 'besthotel-ce019',
    storageBucket: 'besthotel-ce019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ID5LeL8VdYzRsKsrwLbIsHdEaYXdUFM',
    appId: '1:604822129198:ios:7aeccf152e3664ca2e2dbf',
    messagingSenderId: '604822129198',
    projectId: 'besthotel-ce019',
    storageBucket: 'besthotel-ce019.firebasestorage.app',
    iosBundleId: 'com.example.ezapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ID5LeL8VdYzRsKsrwLbIsHdEaYXdUFM',
    appId: '1:604822129198:ios:7aeccf152e3664ca2e2dbf',
    messagingSenderId: '604822129198',
    projectId: 'besthotel-ce019',
    storageBucket: 'besthotel-ce019.firebasestorage.app',
    iosBundleId: 'com.example.ezapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAor9oPLaXeexLRgw6T-AJFSTFYMhLa97g',
    appId: '1:604822129198:web:f0ce4e818db614532e2dbf',
    messagingSenderId: '604822129198',
    projectId: 'besthotel-ce019',
    authDomain: 'besthotel-ce019.firebaseapp.com',
    storageBucket: 'besthotel-ce019.firebasestorage.app',
    measurementId: 'G-9R0BGJBCPN',
  );
}
