import 'package:decimal/decimal.dart';
import 'package:flutter/services.dart';

import '../models/country.dart';
import '../models/country_prefix_code.dart';

class GeneralUtils {
  static double roundToTwo(double val) {
    return double.parse(
      Decimal.parse(val.toStringAsFixed(4)).round(scale: 2).toStringAsFixed(2),
    );
  }

  static FilteringTextInputFormatter allowTwoDecimalPlacesOnly = FilteringTextInputFormatter.allow(RegExp(r'^\d*\.?\d{0,2}'));

  static const List<Country> defaultCountries = [
    Country(
      name: "Malaysia",
      code: "MY",
      flag: "🇲🇾",
      capital: "Kuala Lumpur",
      continent: "Asia",
    ),
    Country(
      name: "Singapore",
      code: "SG",
      flag: "🇸🇬",
      capital: "Singapore",
      continent: "Asia",
    ),
    Country(
      name: "Thailand",
      code: "TH",
      flag: "🇹🇭",
      capital: "Bangkok",
      continent: "Asia",
    ),
    Country(
      name: "China",
      code: "CN",
      flag: "🇨🇳",
      capital: "Beijing",
      continent: "Asia",
    ),
    Country(
      name: "Afghanistan",
      code: "AF",
      flag: "🇦🇫",
      capital: "Kabul",
      continent: "Asia",
    ),
    Country(
      name: "Albania",
      code: "AL",
      flag: "🇦🇱",
      capital: "Tirana",
      continent: "Europe",
    ),
    Country(
      name: "Algeria",
      code: "DZ",
      flag: "🇩🇿",
      capital: "Algiers",
      continent: "Africa",
    ),
    Country(
      name: "Andorra",
      code: "AD",
      flag: "🇦🇩",
      capital: "Andorra la Vella",
      continent: "Europe",
    ),
    Country(
      name: "Angola",
      code: "AO",
      flag: "🇦🇴",
      capital: "Luanda",
      continent: "Africa",
    ),
    Country(
      name: "Antigua and Barbuda",
      code: "AG",
      flag: "🇦🇬",
      capital: "Saint John's",
      continent: "North America",
    ),
    Country(
      name: "Argentina",
      code: "AR",
      flag: "🇦🇷",
      capital: "Buenos Aires",
      continent: "South America",
    ),
    Country(
      name: "Armenia",
      code: "AM",
      flag: "🇦🇲",
      capital: "Yerevan",
      continent: "Asia",
    ),
    Country(
      name: "Australia",
      code: "AU",
      flag: "🇦🇺",
      capital: "Canberra",
      continent: "Oceania",
    ),
    Country(
      name: "Austria",
      code: "AT",
      flag: "🇦🇹",
      capital: "Vienna",
      continent: "Europe",
    ),
    Country(
      name: "Azerbaijan",
      code: "AZ",
      flag: "🇦🇿",
      capital: "Baku",
      continent: "Asia",
    ),
    Country(
      name: "Bahamas",
      code: "BS",
      flag: "🇧🇸",
      capital: "Nassau",
      continent: "North America",
    ),
    Country(
      name: "Bahrain",
      code: "BH",
      flag: "🇧🇭",
      capital: "Manama",
      continent: "Asia",
    ),
    Country(
      name: "Bangladesh",
      code: "BD",
      flag: "🇧🇩",
      capital: "Dhaka",
      continent: "Asia",
    ),
    Country(
      name: "Barbados",
      code: "BB",
      flag: "🇧🇧",
      capital: "Bridgetown",
      continent: "North America",
    ),
    Country(
      name: "Belarus",
      code: "BY",
      flag: "🇧🇾",
      capital: "Minsk",
      continent: "Europe",
    ),
    Country(
      name: "Belgium",
      code: "BE",
      flag: "🇧🇪",
      capital: "Brussels",
      continent: "Europe",
    ),
    Country(
      name: "Belize",
      code: "BZ",
      flag: "🇧🇿",
      capital: "Belmopan",
      continent: "North America",
    ),
    Country(
      name: "Benin",
      code: "BJ",
      flag: "🇧🇯",
      capital: "Porto-Novo",
      continent: "Africa",
    ),
    Country(
      name: "Bhutan",
      code: "BT",
      flag: "🇧🇹",
      capital: "Thimphu",
      continent: "Asia",
    ),
    Country(
      name: "Bolivia",
      code: "BO",
      flag: "🇧🇴",
      capital: "Sucre",
      continent: "South America",
    ),
    Country(
      name: "Bosnia and Herzegovina",
      code: "BA",
      flag: "🇧🇦",
      capital: "Sarajevo",
      continent: "Europe",
    ),
    Country(
      name: "Botswana",
      code: "BW",
      flag: "🇧🇼",
      capital: "Gaborone",
      continent: "Africa",
    ),
    Country(
      name: "Brazil",
      code: "BR",
      flag: "🇧🇷",
      capital: "Brasília",
      continent: "South America",
    ),
    Country(
      name: "Brunei",
      code: "BN",
      flag: "🇧🇳",
      capital: "Bandar Seri Begawan",
      continent: "Asia",
    ),
    Country(
      name: "Bulgaria",
      code: "BG",
      flag: "🇧🇬",
      capital: "Sofia",
      continent: "Europe",
    ),
    Country(
      name: "Burkina Faso",
      code: "BF",
      flag: "🇧🇫",
      capital: "Ouagadougou",
      continent: "Africa",
    ),
    Country(
      name: "Burundi",
      code: "BI",
      flag: "🇧🇮",
      capital: "Gitega",
      continent: "Africa",
    ),
    Country(
      name: "Cabo Verde",
      code: "CV",
      flag: "🇨🇻",
      capital: "Praia",
      continent: "Africa",
    ),
    Country(
      name: "Cambodia",
      code: "KH",
      flag: "🇰🇭",
      capital: "Phnom Penh",
      continent: "Asia",
    ),
    Country(
      name: "Cameroon",
      code: "CM",
      flag: "🇨🇲",
      capital: "Yaoundé",
      continent: "Africa",
    ),
    Country(
      name: "Canada",
      code: "CA",
      flag: "🇨🇦",
      capital: "Ottawa",
      continent: "North America",
    ),
    Country(
      name: "Central African Republic",
      code: "CF",
      flag: "🇨🇫",
      capital: "Bangui",
      continent: "Africa",
    ),
    Country(
      name: "Chad",
      code: "TD",
      flag: "🇹🇩",
      capital: "N'Djamena",
      continent: "Africa",
    ),
    Country(
      name: "Chile",
      code: "CL",
      flag: "🇨🇱",
      capital: "Santiago",
      continent: "South America",
    ),

    Country(
      name: "Colombia",
      code: "CO",
      flag: "🇨🇴",
      capital: "Bogotá",
      continent: "South America",
    ),
    Country(
      name: "Comoros",
      code: "KM",
      flag: "🇰🇲",
      capital: "Moroni",
      continent: "Africa",
    ),
    Country(
      name: "Congo (Congo-Brazzaville)",
      code: "CG",
      flag: "🇨🇬",
      capital: "Brazzaville",
      continent: "Africa",
    ),
    Country(
      name: "Congo (Democratic Republic)",
      code: "CD",
      flag: "🇨🇩",
      capital: "Kinshasa",
      continent: "Africa",
    ),
    Country(
      name: "Costa Rica",
      code: "CR",
      flag: "🇨🇷",
      capital: "San José",
      continent: "North America",
    ),
    Country(
      name: "Croatia",
      code: "HR",
      flag: "🇭🇷",
      capital: "Zagreb",
      continent: "Europe",
    ),
    Country(
      name: "Cuba",
      code: "CU",
      flag: "🇨🇺",
      capital: "Havana",
      continent: "North America",
    ),
    Country(
      name: "Cyprus",
      code: "CY",
      flag: "🇨🇾",
      capital: "Nicosia",
      continent: "Asia",
    ),
    Country(
      name: "Czechia",
      code: "CZ",
      flag: "🇨🇿",
      capital: "Prague",
      continent: "Europe",
    ),
    Country(
      name: "Denmark",
      code: "DK",
      flag: "🇩🇰",
      capital: "Copenhagen",
      continent: "Europe",
    ),
    Country(
      name: "Djibouti",
      code: "DJ",
      flag: "🇩🇯",
      capital: "Djibouti",
      continent: "Africa",
    ),
    Country(
      name: "Dominica",
      code: "DM",
      flag: "🇩🇲",
      capital: "Roseau",
      continent: "North America",
    ),
    Country(
      name: "Dominican Republic",
      code: "DO",
      flag: "🇩🇴",
      capital: "Santo Domingo",
      continent: "North America",
    ),
    Country(
      name: "Ecuador",
      code: "EC",
      flag: "🇪🇨",
      capital: "Quito",
      continent: "South America",
    ),
    Country(
      name: "Egypt",
      code: "EG",
      flag: "🇪🇬",
      capital: "Cairo",
      continent: "Africa",
    ),
    Country(
      name: "El Salvador",
      code: "SV",
      flag: "🇸🇻",
      capital: "San Salvador",
      continent: "North America",
    ),
    Country(
      name: "Equatorial Guinea",
      code: "GQ",
      flag: "🇬🇶",
      capital: "Malabo",
      continent: "Africa",
    ),
    Country(
      name: "Eritrea",
      code: "ER",
      flag: "🇪🇷",
      capital: "Asmara",
      continent: "Africa",
    ),
    Country(
      name: "Estonia",
      code: "EE",
      flag: "🇪🇪",
      capital: "Tallinn",
      continent: "Europe",
    ),
    Country(
      name: "Eswatini",
      code: "SZ",
      flag: "🇸🇿",
      capital: "Mbabane",
      continent: "Africa",
    ),
    Country(
      name: "Ethiopia",
      code: "ET",
      flag: "🇪🇹",
      capital: "Addis Ababa",
      continent: "Africa",
    ),
    Country(
      name: "Fiji",
      code: "FJ",
      flag: "🇫🇯",
      capital: "Suva",
      continent: "Oceania",
    ),
    Country(
      name: "Finland",
      code: "FI",
      flag: "🇫🇮",
      capital: "Helsinki",
      continent: "Europe",
    ),
    Country(
      name: "France",
      code: "FR",
      flag: "🇫🇷",
      capital: "Paris",
      continent: "Europe",
    ),
    Country(
      name: "Gabon",
      code: "GA",
      flag: "🇬🇦",
      capital: "Libreville",
      continent: "Africa",
    ),
    Country(
      name: "Gambia",
      code: "GM",
      flag: "🇬🇲",
      capital: "Banjul",
      continent: "Africa",
    ),
    Country(
      name: "Georgia",
      code: "GE",
      flag: "🇬🇪",
      capital: "Tbilisi",
      continent: "Asia",
    ),
    Country(
      name: "Germany",
      code: "DE",
      flag: "🇩🇪",
      capital: "Berlin",
      continent: "Europe",
    ),
    Country(
      name: "Ghana",
      code: "GH",
      flag: "🇬🇭",
      capital: "Accra",
      continent: "Africa",
    ),
    Country(
      name: "Greece",
      code: "GR",
      flag: "🇬🇷",
      capital: "Athens",
      continent: "Europe",
    ),
    Country(
      name: "Grenada",
      code: "GD",
      flag: "🇬🇩",
      capital: "Saint George's",
      continent: "North America",
    ),
    Country(
      name: "Guatemala",
      code: "GT",
      flag: "🇬🇹",
      capital: "Guatemala City",
      continent: "North America",
    ),
    Country(
      name: "Guinea",
      code: "GN",
      flag: "🇬🇳",
      capital: "Conakry",
      continent: "Africa",
    ),
    Country(
      name: "Guinea-Bissau",
      code: "GW",
      flag: "🇬🇼",
      capital: "Bissau",
      continent: "Africa",
    ),
    Country(
      name: "Guyana",
      code: "GY",
      flag: "🇬🇾",
      capital: "Georgetown",
      continent: "South America",
    ),
    Country(
      name: "Haiti",
      code: "HT",
      flag: "🇭🇹",
      capital: "Port-au-Prince",
      continent: "North America",
    ),
    Country(
      name: "Honduras",
      code: "HN",
      flag: "🇭🇳",
      capital: "Tegucigalpa",
      continent: "North America",
    ),
    Country(
      name: "Hungary",
      code: "HU",
      flag: "🇭🇺",
      capital: "Budapest",
      continent: "Europe",
    ),
    Country(
      name: "Iceland",
      code: "IS",
      flag: "🇮🇸",
      capital: "Reykjavík",
      continent: "Europe",
    ),
    Country(
      name: "India",
      code: "IN",
      flag: "🇮🇳",
      capital: "New Delhi",
      continent: "Asia",
    ),
    Country(
      name: "Indonesia",
      code: "ID",
      flag: "🇮🇩",
      capital: "Jakarta",
      continent: "Asia",
    ),
    Country(
      name: "Iran",
      code: "IR",
      flag: "🇮🇷",
      capital: "Tehran",
      continent: "Asia",
    ),
    Country(
      name: "Iraq",
      code: "IQ",
      flag: "🇮🇶",
      capital: "Baghdad",
      continent: "Asia",
    ),
    Country(
      name: "Ireland",
      code: "IE",
      flag: "🇮🇪",
      capital: "Dublin",
      continent: "Europe",
    ),
    Country(
      name: "Israel",
      code: "IL",
      flag: "🇮🇱",
      capital: "Jerusalem",
      continent: "Asia",
    ),
    Country(
      name: "Italy",
      code: "IT",
      flag: "🇮🇹",
      capital: "Rome",
      continent: "Europe",
    ),
    Country(
      name: "Jamaica",
      code: "JM",
      flag: "🇯🇲",
      capital: "Kingston",
      continent: "North America",
    ),
    Country(
      name: "Japan",
      code: "JP",
      flag: "🇯🇵",
      capital: "Tokyo",
      continent: "Asia",
    ),
    Country(
      name: "Jordan",
      code: "JO",
      flag: "🇯🇴",
      capital: "Amman",
      continent: "Asia",
    ),
    Country(
      name: "Kazakhstan",
      code: "KZ",
      flag: "🇰🇿",
      capital: "Astana",
      continent: "Asia",
    ),
    Country(
      name: "Kenya",
      code: "KE",
      flag: "🇰🇪",
      capital: "Nairobi",
      continent: "Africa",
    ),
    Country(
      name: "Kiribati",
      code: "KI",
      flag: "🇰🇮",
      capital: "South Tarawa",
      continent: "Oceania",
    ),
    Country(
      name: "Kuwait",
      code: "KW",
      flag: "🇰🇼",
      capital: "Kuwait City",
      continent: "Asia",
    ),
    Country(
      name: "Kyrgyzstan",
      code: "KG",
      flag: "🇰🇬",
      capital: "Bishkek",
      continent: "Asia",
    ),
    Country(
      name: "Laos",
      code: "LA",
      flag: "🇱🇦",
      capital: "Vientiane",
      continent: "Asia",
    ),
    Country(
      name: "Latvia",
      code: "LV",
      flag: "🇱🇻",
      capital: "Riga",
      continent: "Europe",
    ),
    Country(
      name: "Lebanon",
      code: "LB",
      flag: "🇱🇧",
      capital: "Beirut",
      continent: "Asia",
    ),
    Country(
      name: "Lesotho",
      code: "LS",
      flag: "🇱🇸",
      capital: "Maseru",
      continent: "Africa",
    ),
    Country(
      name: "Liberia",
      code: "LR",
      flag: "🇱🇷",
      capital: "Monrovia",
      continent: "Africa",
    ),
    Country(
      name: "Libya",
      code: "LY",
      flag: "🇱🇾",
      capital: "Tripoli",
      continent: "Africa",
    ),
    Country(
      name: "Liechtenstein",
      code: "LI",
      flag: "🇱🇮",
      capital: "Vaduz",
      continent: "Europe",
    ),
    Country(
      name: "Lithuania",
      code: "LT",
      flag: "🇱🇹",
      capital: "Vilnius",
      continent: "Europe",
    ),
    Country(
      name: "Luxembourg",
      code: "LU",
      flag: "🇱🇺",
      capital: "Luxembourg City",
      continent: "Europe",
    ),
    Country(
      name: "Madagascar",
      code: "MG",
      flag: "🇲🇬",
      capital: "Antananarivo",
      continent: "Africa",
    ),
    Country(
      name: "Malawi",
      code: "MW",
      flag: "🇲🇼",
      capital: "Lilongwe",
      continent: "Africa",
    ),

    Country(
      name: "Maldives",
      code: "MV",
      flag: "🇲🇻",
      capital: "Malé",
      continent: "Asia",
    ),
    Country(
      name: "Mali",
      code: "ML",
      flag: "🇲🇱",
      capital: "Bamako",
      continent: "Africa",
    ),
    Country(
      name: "Malta",
      code: "MT",
      flag: "🇲🇹",
      capital: "Valletta",
      continent: "Europe",
    ),
    Country(
      name: "Marshall Islands",
      code: "MH",
      flag: "🇲🇭",
      capital: "Majuro",
      continent: "Oceania",
    ),
    Country(
      name: "Mauritania",
      code: "MR",
      flag: "🇲🇷",
      capital: "Nouakchott",
      continent: "Africa",
    ),
    Country(
      name: "Mauritius",
      code: "MU",
      flag: "🇲🇺",
      capital: "Port Louis",
      continent: "Africa",
    ),
    Country(
      name: "Mexico",
      code: "MX",
      flag: "🇲🇽",
      capital: "Mexico City",
      continent: "North America",
    ),
    Country(
      name: "Micronesia",
      code: "FM",
      flag: "🇫🇲",
      capital: "Palikir",
      continent: "Oceania",
    ),
    Country(
      name: "Moldova",
      code: "MD",
      flag: "🇲🇩",
      capital: "Chișinău",
      continent: "Europe",
    ),
    Country(
      name: "Monaco",
      code: "MC",
      flag: "🇲🇨",
      capital: "Monaco",
      continent: "Europe",
    ),
    Country(
      name: "Mongolia",
      code: "MN",
      flag: "🇲🇳",
      capital: "Ulaanbaatar",
      continent: "Asia",
    ),
    Country(
      name: "Montenegro",
      code: "ME",
      flag: "🇲🇪",
      capital: "Podgorica",
      continent: "Europe",
    ),
    Country(
      name: "Morocco",
      code: "MA",
      flag: "🇲🇦",
      capital: "Rabat",
      continent: "Africa",
    ),
    Country(
      name: "Mozambique",
      code: "MZ",
      flag: "🇲🇿",
      capital: "Maputo",
      continent: "Africa",
    ),
    Country(
      name: "Myanmar",
      code: "MM",
      flag: "🇲🇲",
      capital: "Naypyidaw",
      continent: "Asia",
    ),
    Country(
      name: "Namibia",
      code: "NA",
      flag: "🇳🇦",
      capital: "Windhoek",
      continent: "Africa",
    ),
    Country(
      name: "Nauru",
      code: "NR",
      flag: "🇳🇷",
      capital: "Yaren District",
      continent: "Oceania",
    ),
    Country(
      name: "Nepal",
      code: "NP",
      flag: "🇳🇵",
      capital: "Kathmandu",
      continent: "Asia",
    ),
    Country(
      name: "Netherlands",
      code: "NL",
      flag: "🇳🇱",
      capital: "Amsterdam",
      continent: "Europe",
    ),
    Country(
      name: "New Zealand",
      code: "NZ",
      flag: "🇳🇿",
      capital: "Wellington",
      continent: "Oceania",
    ),
    Country(
      name: "Nicaragua",
      code: "NI",
      flag: "🇳🇮",
      capital: "Managua",
      continent: "North America",
    ),
    Country(
      name: "Niger",
      code: "NE",
      flag: "🇳🇪",
      capital: "Niamey",
      continent: "Africa",
    ),
    Country(
      name: "Nigeria",
      code: "NG",
      flag: "🇳🇬",
      capital: "Abuja",
      continent: "Africa",
    ),
    Country(
      name: "North Korea",
      code: "KP",
      flag: "🇰🇵",
      capital: "Pyongyang",
      continent: "Asia",
    ),
    Country(
      name: "North Macedonia",
      code: "MK",
      flag: "🇲🇰",
      capital: "Skopje",
      continent: "Europe",
    ),
    Country(
      name: "Norway",
      code: "NO",
      flag: "🇳🇴",
      capital: "Oslo",
      continent: "Europe",
    ),
    Country(
      name: "Oman",
      code: "OM",
      flag: "🇴🇲",
      capital: "Muscat",
      continent: "Asia",
    ),
    Country(
      name: "Pakistan",
      code: "PK",
      flag: "🇵🇰",
      capital: "Islamabad",
      continent: "Asia",
    ),
    Country(
      name: "Palau",
      code: "PW",
      flag: "🇵🇼",
      capital: "Ngerulmud",
      continent: "Oceania",
    ),
    Country(
      name: "Palestine",
      code: "PS",
      flag: "🇵🇸",
      capital: "East Jerusalem",
      continent: "Asia",
    ),
    Country(
      name: "Panama",
      code: "PA",
      flag: "🇵🇦",
      capital: "Panama City",
      continent: "North America",
    ),
    Country(
      name: "Papua New Guinea",
      code: "PG",
      flag: "🇵🇬",
      capital: "Port Moresby",
      continent: "Oceania",
    ),
    Country(
      name: "Paraguay",
      code: "PY",
      flag: "🇵🇾",
      capital: "Asunción",
      continent: "South America",
    ),
    Country(
      name: "Peru",
      code: "PE",
      flag: "🇵🇪",
      capital: "Lima",
      continent: "South America",
    ),
    Country(
      name: "Philippines",
      code: "PH",
      flag: "🇵🇭",
      capital: "Manila",
      continent: "Asia",
    ),
    Country(
      name: "Poland",
      code: "PL",
      flag: "🇵🇱",
      capital: "Warsaw",
      continent: "Europe",
    ),
    Country(
      name: "Portugal",
      code: "PT",
      flag: "🇵🇹",
      capital: "Lisbon",
      continent: "Europe",
    ),
    Country(
      name: "Qatar",
      code: "QA",
      flag: "🇶🇦",
      capital: "Doha",
      continent: "Asia",
    ),
    Country(
      name: "Romania",
      code: "RO",
      flag: "🇷🇴",
      capital: "Bucharest",
      continent: "Europe",
    ),
    Country(
      name: "Russia",
      code: "RU",
      flag: "🇷🇺",
      capital: "Moscow",
      continent: "Europe",
    ),
    Country(
      name: "Rwanda",
      code: "RW",
      flag: "🇷🇼",
      capital: "Kigali",
      continent: "Africa",
    ),
    Country(
      name: "Saint Kitts and Nevis",
      code: "KN",
      flag: "🇰🇳",
      capital: "Basseterre",
      continent: "North America",
    ),
    Country(
      name: "Saint Lucia",
      code: "LC",
      flag: "🇱🇨",
      capital: "Castries",
      continent: "North America",
    ),
    Country(
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      flag: "🇻🇨",
      capital: "Kingstown",
      continent: "North America",
    ),
    Country(
      name: "Samoa",
      code: "WS",
      flag: "🇼🇸",
      capital: "Apia",
      continent: "Oceania",
    ),
    Country(
      name: "San Marino",
      code: "SM",
      flag: "🇸🇲",
      capital: "San Marino",
      continent: "Europe",
    ),
    Country(
      name: "Sao Tome and Principe",
      code: "ST",
      flag: "🇸🇹",
      capital: "São Tomé",
      continent: "Africa",
    ),
    Country(
      name: "Saudi Arabia",
      code: "SA",
      flag: "🇸🇦",
      capital: "Riyadh",
      continent: "Asia",
    ),
    Country(
      name: "Senegal",
      code: "SN",
      flag: "🇸🇳",
      capital: "Dakar",
      continent: "Africa",
    ),
    Country(
      name: "Serbia",
      code: "RS",
      flag: "🇷🇸",
      capital: "Belgrade",
      continent: "Europe",
    ),
    Country(
      name: "Seychelles",
      code: "SC",
      flag: "🇸🇨",
      capital: "Victoria",
      continent: "Africa",
    ),
    Country(
      name: "Sierra Leone",
      code: "SL",
      flag: "🇸🇱",
      capital: "Freetown",
      continent: "Africa",
    ),

    Country(
      name: "Slovakia",
      code: "SK",
      flag: "🇸🇰",
      capital: "Bratislava",
      continent: "Europe",
    ),
    Country(
      name: "Slovenia",
      code: "SI",
      flag: "🇸🇮",
      capital: "Ljubljana",
      continent: "Europe",
    ),
    Country(
      name: "Solomon Islands",
      code: "SB",
      flag: "🇸🇧",
      capital: "Honiara",
      continent: "Oceania",
    ),
    Country(
      name: "Somalia",
      code: "SO",
      flag: "🇸🇴",
      capital: "Mogadishu",
      continent: "Africa",
    ),
    Country(
      name: "South Africa",
      code: "ZA",
      flag: "🇿🇦",
      capital: "Pretoria",
      continent: "Africa",
    ),
    Country(
      name: "South Korea",
      code: "KR",
      flag: "🇰🇷",
      capital: "Seoul",
      continent: "Asia",
    ),
    Country(
      name: "South Sudan",
      code: "SS",
      flag: "🇸🇸",
      capital: "Juba",
      continent: "Africa",
    ),
    Country(
      name: "Spain",
      code: "ES",
      flag: "🇪🇸",
      capital: "Madrid",
      continent: "Europe",
    ),
    Country(
      name: "Sri Lanka",
      code: "LK",
      flag: "🇱🇰",
      capital: "Sri Jayawardenepura Kotte",
      continent: "Asia",
    ),
    Country(
      name: "Sudan",
      code: "SD",
      flag: "🇸🇩",
      capital: "Khartoum",
      continent: "Africa",
    ),
    Country(
      name: "Suriname",
      code: "SR",
      flag: "🇸🇷",
      capital: "Paramaribo",
      continent: "South America",
    ),
    Country(
      name: "Sweden",
      code: "SE",
      flag: "🇸🇪",
      capital: "Stockholm",
      continent: "Europe",
    ),
    Country(
      name: "Switzerland",
      code: "CH",
      flag: "🇨🇭",
      capital: "Bern",
      continent: "Europe",
    ),
    Country(
      name: "Syria",
      code: "SY",
      flag: "🇸🇾",
      capital: "Damascus",
      continent: "Asia",
    ),
    Country(
      name: "Taiwan",
      code: "TW",
      flag: "🇹🇼",
      capital: "Taipei",
      continent: "Asia",
    ),
    Country(
      name: "Tajikistan",
      code: "TJ",
      flag: "🇹🇯",
      capital: "Dushanbe",
      continent: "Asia",
    ),
    Country(
      name: "Tanzania",
      code: "TZ",
      flag: "🇹🇿",
      capital: "Dodoma",
      continent: "Africa",
    ),

    Country(
      name: "Togo",
      code: "TG",
      flag: "🇹🇬",
      capital: "Lomé",
      continent: "Africa",
    ),
    Country(
      name: "Tonga",
      code: "TO",
      flag: "🇹🇴",
      capital: "Nukuʻalofa",
      continent: "Oceania",
    ),
    Country(
      name: "Trinidad and Tobago",
      code: "TT",
      flag: "🇹🇹",
      capital: "Port of Spain",
      continent: "North America",
    ),
    Country(
      name: "Tunisia",
      code: "TN",
      flag: "🇹🇳",
      capital: "Tunis",
      continent: "Africa",
    ),
    Country(
      name: "Turkey",
      code: "TR",
      flag: "🇹🇷",
      capital: "Ankara",
      continent: "Asia",
    ),
    Country(
      name: "Turkmenistan",
      code: "TM",
      flag: "🇹🇲",
      capital: "Ashgabat",
      continent: "Asia",
    ),
    Country(
      name: "Tuvalu",
      code: "TV",
      flag: "🇹🇻",
      capital: "Funafuti",
      continent: "Oceania",
    ),
    Country(
      name: "Uganda",
      code: "UG",
      flag: "🇺🇬",
      capital: "Kampala",
      continent: "Africa",
    ),
    Country(
      name: "Ukraine",
      code: "UA",
      flag: "🇺🇦",
      capital: "Kyiv",
      continent: "Europe",
    ),
    Country(
      name: "United Arab Emirates",
      code: "AE",
      flag: "🇦🇪",
      capital: "Abu Dhabi",
      continent: "Asia",
    ),
    Country(
      name: "United Kingdom",
      code: "GB",
      flag: "🇬🇧",
      capital: "London",
      continent: "Europe",
    ),
    Country(
      name: "United States",
      code: "US",
      flag: "🇺🇸",
      capital: "Washington, D.C.",
      continent: "North America",
    ),
    Country(
      name: "Uruguay",
      code: "UY",
      flag: "🇺🇾",
      capital: "Montevideo",
      continent: "South America",
    ),
    Country(
      name: "Uzbekistan",
      code: "UZ",
      flag: "🇺🇿",
      capital: "Tashkent",
      continent: "Asia",
    ),
    Country(
      name: "Vanuatu",
      code: "VU",
      flag: "🇻🇺",
      capital: "Port Vila",
      continent: "Oceania",
    ),
    Country(
      name: "Vatican City",
      code: "VA",
      flag: "🇻🇦",
      capital: "Vatican City",
      continent: "Europe",
    ),
    Country(
      name: "Venezuela",
      code: "VE",
      flag: "🇻🇪",
      capital: "Caracas",
      continent: "South America",
    ),
    Country(
      name: "Vietnam",
      code: "VN",
      flag: "🇻🇳",
      capital: "Hanoi",
      continent: "Asia",
    ),
    Country(
      name: "Yemen",
      code: "YE",
      flag: "🇾🇪",
      capital: "Sana'a",
      continent: "Asia",
    ),
    Country(
      name: "Zambia",
      code: "ZM",
      flag: "🇿🇲",
      capital: "Lusaka",
      continent: "Africa",
    ),
    Country(
      name: "Zimbabwe",
      code: "ZW",
      flag: "🇿🇼",
      capital: "Harare",
      continent: "Africa",
    ),
  ];

  static List<CountryPrefixCode> countryPrefixCodes = [
    CountryPrefixCode(
      name: "Malaysia",
      code: "MY",
      dialCode: "+60",
      flag: "🇲🇾",
    ),
    CountryPrefixCode(
      name: "Singapore",
      code: "SG",
      dialCode: "+65",
      flag: "🇸🇬",
    ),
    CountryPrefixCode(
      name: "Thailand",
      code: "TH",
      dialCode: "+66",
      flag: "🇹🇭",
    ),
    CountryPrefixCode(name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳"),
    CountryPrefixCode(
      name: "Afghanistan",
      code: "AF",
      dialCode: "+93",
      flag: "🇦🇫",
    ),
    CountryPrefixCode(
      name: "Åland Islands",
      code: "AX",
      dialCode: "+358",
      flag: "🇦🇽",
    ),
    CountryPrefixCode(
      name: "Albania",
      code: "AL",
      dialCode: "+355",
      flag: "🇦🇱",
    ),
    CountryPrefixCode(
      name: "Algeria",
      code: "DZ",
      dialCode: "+213",
      flag: "🇩🇿",
    ),
    CountryPrefixCode(
      name: "American Samoa",
      code: "AS",
      dialCode: "+1-684",
      flag: "🇦🇸",
    ),
    CountryPrefixCode(
      name: "Andorra",
      code: "AD",
      dialCode: "+376",
      flag: "🇦🇩",
    ),
    CountryPrefixCode(
      name: "Angola",
      code: "AO",
      dialCode: "+244",
      flag: "🇦🇴",
    ),
    CountryPrefixCode(
      name: "Anguilla",
      code: "AI",
      dialCode: "+1-264",
      flag: "🇦🇮",
    ),
    CountryPrefixCode(
      name: "Antarctica",
      code: "AQ",
      dialCode: "+672",
      flag: "🇦🇶",
    ),
    CountryPrefixCode(
      name: "Antigua and Barbuda",
      code: "AG",
      dialCode: "+1-268",
      flag: "🇦🇬",
    ),
    CountryPrefixCode(
      name: "Argentina",
      code: "AR",
      dialCode: "+54",
      flag: "🇦🇷",
    ),
    CountryPrefixCode(
      name: "Armenia",
      code: "AM",
      dialCode: "+374",
      flag: "🇦🇲",
    ),
    CountryPrefixCode(
      name: "Aruba",
      code: "AW",
      dialCode: "+297",
      flag: "🇦🇼",
    ),
    CountryPrefixCode(
      name: "Australia",
      code: "AU",
      dialCode: "+61",
      flag: "🇦🇺",
    ),
    CountryPrefixCode(
      name: "Austria",
      code: "AT",
      dialCode: "+43",
      flag: "🇦🇹",
    ),
    CountryPrefixCode(
      name: "Azerbaijan",
      code: "AZ",
      dialCode: "+994",
      flag: "🇦🇿",
    ),
    CountryPrefixCode(
      name: "Bahamas",
      code: "BS",
      dialCode: "+1-242",
      flag: "🇧🇸",
    ),
    CountryPrefixCode(
      name: "Bahrain",
      code: "BH",
      dialCode: "+973",
      flag: "🇧🇭",
    ),
    CountryPrefixCode(
      name: "Bangladesh",
      code: "BD",
      dialCode: "+880",
      flag: "🇧🇩",
    ),
    CountryPrefixCode(
      name: "Barbados",
      code: "BB",
      dialCode: "+1-246",
      flag: "🇧🇧",
    ),
    CountryPrefixCode(
      name: "Belarus",
      code: "BY",
      dialCode: "+375",
      flag: "🇧🇾",
    ),
    CountryPrefixCode(
      name: "Belgium",
      code: "BE",
      dialCode: "+32",
      flag: "🇧🇪",
    ),
    CountryPrefixCode(
      name: "Belize",
      code: "BZ",
      dialCode: "+501",
      flag: "🇧🇿",
    ),
    CountryPrefixCode(
      name: "Benin",
      code: "BJ",
      dialCode: "+229",
      flag: "🇧🇯",
    ),
    CountryPrefixCode(
      name: "Bermuda",
      code: "BM",
      dialCode: "+1-441",
      flag: "🇧🇲",
    ),
    CountryPrefixCode(
      name: "Bhutan",
      code: "BT",
      dialCode: "+975",
      flag: "🇧🇹",
    ),
    CountryPrefixCode(
      name: "Bolivia",
      code: "BO",
      dialCode: "+591",
      flag: "🇧🇴",
    ),
    CountryPrefixCode(
      name: "Bonaire, Sint Eustatius and Saba",
      code: "BQ",
      dialCode: "+599",
      flag: "🇧🇶",
    ),
    CountryPrefixCode(
      name: "Bosnia and Herzegovina",
      code: "BA",
      dialCode: "+387",
      flag: "🇧🇦",
    ),
    CountryPrefixCode(
      name: "Botswana",
      code: "BW",
      dialCode: "+267",
      flag: "🇧🇼",
    ),
    CountryPrefixCode(
      name: "Bouvet Island",
      code: "BV",
      dialCode: "+47",
      flag: "🇧🇻",
    ),
    CountryPrefixCode(
      name: "Brazil",
      code: "BR",
      dialCode: "+55",
      flag: "🇧🇷",
    ),
    CountryPrefixCode(
      name: "British Indian Ocean Territory",
      code: "IO",
      dialCode: "+246",
      flag: "🇮🇴",
    ),
    CountryPrefixCode(
      name: "Brunei Darussalam",
      code: "BN",
      dialCode: "+673",
      flag: "🇧🇳",
    ),
    CountryPrefixCode(
      name: "Bulgaria",
      code: "BG",
      dialCode: "+359",
      flag: "🇧🇬",
    ),
    CountryPrefixCode(
      name: "Burkina Faso",
      code: "BF",
      dialCode: "+226",
      flag: "🇧🇫",
    ),
    CountryPrefixCode(
      name: "Burundi",
      code: "BI",
      dialCode: "+257",
      flag: "🇧🇮",
    ),
    CountryPrefixCode(
      name: "Cabo Verde",
      code: "CV",
      dialCode: "+238",
      flag: "🇨🇻",
    ),
    CountryPrefixCode(
      name: "Cambodia",
      code: "KH",
      dialCode: "+855",
      flag: "🇰🇭",
    ),
    CountryPrefixCode(
      name: "Cameroon",
      code: "CM",
      dialCode: "+237",
      flag: "🇨🇲",
    ),
    CountryPrefixCode(name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦"),
    CountryPrefixCode(
      name: "Cayman Islands",
      code: "KY",
      dialCode: "+1-345",
      flag: "🇰🇾",
    ),
    CountryPrefixCode(
      name: "Central African Republic",
      code: "CF",
      dialCode: "+236",
      flag: "🇨🇫",
    ),
    CountryPrefixCode(name: "Chad", code: "TD", dialCode: "+235", flag: "🇹🇩"),
    CountryPrefixCode(name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱"),
    CountryPrefixCode(
      name: "Christmas Island",
      code: "CX",
      dialCode: "+61",
      flag: "🇨🇽",
    ),
    CountryPrefixCode(
      name: "Cocos (Keeling) Islands",
      code: "CC",
      dialCode: "+61",
      flag: "🇨🇨",
    ),
    CountryPrefixCode(
      name: "Colombia",
      code: "CO",
      dialCode: "+57",
      flag: "🇨🇴",
    ),
    CountryPrefixCode(
      name: "Comoros",
      code: "KM",
      dialCode: "+269",
      flag: "🇰🇲",
    ),
    CountryPrefixCode(
      name: "Congo",
      code: "CG",
      dialCode: "+242",
      flag: "🇨🇬",
    ),
    CountryPrefixCode(
      name: "Congo (Democratic Republic)",
      code: "CD",
      dialCode: "+243",
      flag: "🇨🇩",
    ),
    CountryPrefixCode(
      name: "Cook Islands",
      code: "CK",
      dialCode: "+682",
      flag: "🇨🇰",
    ),
    CountryPrefixCode(
      name: "Costa Rica",
      code: "CR",
      dialCode: "+506",
      flag: "🇨🇷",
    ),
    CountryPrefixCode(
      name: "Côte d'Ivoire",
      code: "CI",
      dialCode: "+225",
      flag: "🇨🇮",
    ),
    CountryPrefixCode(
      name: "Croatia",
      code: "HR",
      dialCode: "+385",
      flag: "🇭🇷",
    ),
    CountryPrefixCode(name: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺"),
    CountryPrefixCode(
      name: "Curaçao",
      code: "CW",
      dialCode: "+599",
      flag: "🇨🇼",
    ),
    CountryPrefixCode(
      name: "Cyprus",
      code: "CY",
      dialCode: "+357",
      flag: "🇨🇾",
    ),
    CountryPrefixCode(
      name: "Czech Republic",
      code: "CZ",
      dialCode: "+420",
      flag: "🇨🇿",
    ),
    CountryPrefixCode(
      name: "Denmark",
      code: "DK",
      dialCode: "+45",
      flag: "🇩🇰",
    ),
    CountryPrefixCode(
      name: "Djibouti",
      code: "DJ",
      dialCode: "+253",
      flag: "🇩🇯",
    ),
    CountryPrefixCode(
      name: "Dominica",
      code: "DM",
      dialCode: "+1-767",
      flag: "🇩🇲",
    ),
    CountryPrefixCode(
      name: "Dominican Republic",
      code: "DO",
      dialCode: "+1-809",
      flag: "🇩🇴",
    ),
    CountryPrefixCode(
      name: "Ecuador",
      code: "EC",
      dialCode: "+593",
      flag: "🇪🇨",
    ),
    CountryPrefixCode(name: "Egypt", code: "EG", dialCode: "+20", flag: "🇪🇬"),
    CountryPrefixCode(
      name: "El Salvador",
      code: "SV",
      dialCode: "+503",
      flag: "🇸🇻",
    ),
    CountryPrefixCode(
      name: "Equatorial Guinea",
      code: "GQ",
      dialCode: "+240",
      flag: "🇬🇶",
    ),
    CountryPrefixCode(
      name: "Eritrea",
      code: "ER",
      dialCode: "+291",
      flag: "🇪🇷",
    ),
    CountryPrefixCode(
      name: "Estonia",
      code: "EE",
      dialCode: "+372",
      flag: "🇪🇪",
    ),
    CountryPrefixCode(
      name: "Eswatini",
      code: "SZ",
      dialCode: "+268",
      flag: "🇸🇿",
    ),
    CountryPrefixCode(
      name: "Ethiopia",
      code: "ET",
      dialCode: "+251",
      flag: "🇪🇹",
    ),
    CountryPrefixCode(
      name: "Falkland Islands (Malvinas)",
      code: "FK",
      dialCode: "+500",
      flag: "🇫🇰",
    ),
    CountryPrefixCode(
      name: "Faroe Islands",
      code: "FO",
      dialCode: "+298",
      flag: "🇫🇴",
    ),
    CountryPrefixCode(name: "Fiji", code: "FJ", dialCode: "+679", flag: "🇫🇯"),
    CountryPrefixCode(
      name: "Finland",
      code: "FI",
      dialCode: "+358",
      flag: "🇫🇮",
    ),
    CountryPrefixCode(
      name: "France",
      code: "FR",
      dialCode: "+33",
      flag: "🇫🇷",
    ),
    CountryPrefixCode(
      name: "French Guiana",
      code: "GF",
      dialCode: "+594",
      flag: "🇬🇫",
    ),
    CountryPrefixCode(
      name: "French Polynesia",
      code: "PF",
      dialCode: "+689",
      flag: "🇵🇫",
    ),
    CountryPrefixCode(
      name: "French Southern Territories",
      code: "TF",
      dialCode: "+262",
      flag: "🇹🇫",
    ),
    CountryPrefixCode(
      name: "Gabon",
      code: "GA",
      dialCode: "+241",
      flag: "🇬🇦",
    ),
    CountryPrefixCode(
      name: "Gambia",
      code: "GM",
      dialCode: "+220",
      flag: "🇬🇲",
    ),
    CountryPrefixCode(
      name: "Georgia",
      code: "GE",
      dialCode: "+995",
      flag: "🇬🇪",
    ),
    CountryPrefixCode(
      name: "Germany",
      code: "DE",
      dialCode: "+49",
      flag: "🇩🇪",
    ),
    CountryPrefixCode(
      name: "Ghana",
      code: "GH",
      dialCode: "+233",
      flag: "🇬🇭",
    ),
    CountryPrefixCode(
      name: "Gibraltar",
      code: "GI",
      dialCode: "+350",
      flag: "🇬🇮",
    ),
    CountryPrefixCode(
      name: "Greece",
      code: "GR",
      dialCode: "+30",
      flag: "🇬🇷",
    ),
    CountryPrefixCode(
      name: "Greenland",
      code: "GL",
      dialCode: "+299",
      flag: "🇬🇱",
    ),
    CountryPrefixCode(
      name: "Grenada",
      code: "GD",
      dialCode: "+1-473",
      flag: "🇬🇩",
    ),
    CountryPrefixCode(
      name: "Guadeloupe",
      code: "GP",
      dialCode: "+590",
      flag: "🇬🇵",
    ),
    CountryPrefixCode(
      name: "Guam",
      code: "GU",
      dialCode: "+1-671",
      flag: "🇬🇺",
    ),
    CountryPrefixCode(
      name: "Guatemala",
      code: "GT",
      dialCode: "+502",
      flag: "🇬🇹",
    ),
    CountryPrefixCode(
      name: "Guernsey",
      code: "GG",
      dialCode: "+44-1481",
      flag: "🇬🇬",
    ),
    CountryPrefixCode(
      name: "Guinea",
      code: "GN",
      dialCode: "+224",
      flag: "🇬🇳",
    ),
    CountryPrefixCode(
      name: "Guinea-Bissau",
      code: "GW",
      dialCode: "+245",
      flag: "🇬🇼",
    ),
    CountryPrefixCode(
      name: "Guyana",
      code: "GY",
      dialCode: "+592",
      flag: "🇬🇾",
    ),
    CountryPrefixCode(
      name: "Haiti",
      code: "HT",
      dialCode: "+509",
      flag: "🇭🇹",
    ),
    CountryPrefixCode(
      name: "Heard Island and McDonald Islands",
      code: "HM",
      dialCode: "+672",
      flag: "🇭🇲",
    ),
    CountryPrefixCode(
      name: "Holy See (Vatican City State)",
      code: "VA",
      dialCode: "+379",
      flag: "🇻🇦",
    ),
    CountryPrefixCode(
      name: "Honduras",
      code: "HN",
      dialCode: "+504",
      flag: "🇭🇳",
    ),
    CountryPrefixCode(
      name: "Hong Kong",
      code: "HK",
      dialCode: "+852",
      flag: "🇭🇰",
    ),
    CountryPrefixCode(
      name: "Hungary",
      code: "HU",
      dialCode: "+36",
      flag: "🇭🇺",
    ),
    CountryPrefixCode(
      name: "Iceland",
      code: "IS",
      dialCode: "+354",
      flag: "🇮🇸",
    ),
    CountryPrefixCode(name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳"),
    CountryPrefixCode(
      name: "Indonesia",
      code: "ID",
      dialCode: "+62",
      flag: "🇮🇩",
    ),
    CountryPrefixCode(name: "Iran", code: "IR", dialCode: "+98", flag: "🇮🇷"),
    CountryPrefixCode(name: "Iraq", code: "IQ", dialCode: "+964", flag: "🇮🇶"),
    CountryPrefixCode(
      name: "Ireland",
      code: "IE",
      dialCode: "+353",
      flag: "🇮🇪",
    ),
    CountryPrefixCode(
      name: "Isle of Man",
      code: "IM",
      dialCode: "+44-1624",
      flag: "🇮🇲",
    ),
    CountryPrefixCode(
      name: "Israel",
      code: "IL",
      dialCode: "+972",
      flag: "🇮🇱",
    ),
    CountryPrefixCode(name: "Italy", code: "IT", dialCode: "+39", flag: "🇮🇹"),
    CountryPrefixCode(
      name: "Jamaica",
      code: "JM",
      dialCode: "+1-876",
      flag: "🇯🇲",
    ),
    CountryPrefixCode(name: "Japan", code: "JP", dialCode: "+81", flag: "🇯🇵"),
    CountryPrefixCode(
      name: "Jersey",
      code: "JE",
      dialCode: "+44-1534",
      flag: "🇯🇪",
    ),
    CountryPrefixCode(
      name: "Jordan",
      code: "JO",
      dialCode: "+962",
      flag: "🇯🇴",
    ),
    CountryPrefixCode(
      name: "Kazakhstan",
      code: "KZ",
      dialCode: "+7",
      flag: "🇰🇿",
    ),
    CountryPrefixCode(
      name: "Kenya",
      code: "KE",
      dialCode: "+254",
      flag: "🇰🇪",
    ),
    CountryPrefixCode(
      name: "Kiribati",
      code: "KI",
      dialCode: "+686",
      flag: "🇰🇮",
    ),
    CountryPrefixCode(
      name: "Kuwait",
      code: "KW",
      dialCode: "+965",
      flag: "🇰🇼",
    ),
    CountryPrefixCode(
      name: "Kyrgyzstan",
      code: "KG",
      dialCode: "+996",
      flag: "🇰🇬",
    ),
    CountryPrefixCode(name: "Laos", code: "LA", dialCode: "+856", flag: "🇱🇦"),
    CountryPrefixCode(
      name: "Latvia",
      code: "LV",
      dialCode: "+371",
      flag: "🇱🇻",
    ),
    CountryPrefixCode(
      name: "Lebanon",
      code: "LB",
      dialCode: "+961",
      flag: "🇱🇧",
    ),
    CountryPrefixCode(
      name: "Lesotho",
      code: "LS",
      dialCode: "+266",
      flag: "🇱🇸",
    ),
    CountryPrefixCode(
      name: "Liberia",
      code: "LR",
      dialCode: "+231",
      flag: "🇱🇷",
    ),
    CountryPrefixCode(
      name: "Libya",
      code: "LY",
      dialCode: "+218",
      flag: "🇱🇾",
    ),
    CountryPrefixCode(
      name: "Liechtenstein",
      code: "LI",
      dialCode: "+423",
      flag: "🇱🇮",
    ),
    CountryPrefixCode(
      name: "Lithuania",
      code: "LT",
      dialCode: "+370",
      flag: "🇱🇹",
    ),
    CountryPrefixCode(
      name: "Luxembourg",
      code: "LU",
      dialCode: "+352",
      flag: "🇱🇺",
    ),
    CountryPrefixCode(
      name: "Macao",
      code: "MO",
      dialCode: "+853",
      flag: "🇲🇴",
    ),
    CountryPrefixCode(
      name: "Macedonia (North Macedonia)",
      code: "MK",
      dialCode: "+389",
      flag: "🇲🇰",
    ),
    CountryPrefixCode(
      name: "Madagascar",
      code: "MG",
      dialCode: "+261",
      flag: "🇲🇬",
    ),
    CountryPrefixCode(
      name: "Malawi",
      code: "MW",
      dialCode: "+265",
      flag: "🇲🇼",
    ),
    CountryPrefixCode(
      name: "Maldives",
      code: "MV",
      dialCode: "+960",
      flag: "🇲🇻",
    ),
    CountryPrefixCode(name: "Mali", code: "ML", dialCode: "+223", flag: "🇲🇱"),
    CountryPrefixCode(
      name: "Malta",
      code: "MT",
      dialCode: "+356",
      flag: "🇲🇹",
    ),
    CountryPrefixCode(
      name: "Marshall Islands",
      code: "MH",
      dialCode: "+692",
      flag: "🇲🇭",
    ),
    CountryPrefixCode(
      name: "Martinique",
      code: "MQ",
      dialCode: "+596",
      flag: "🇲🇶",
    ),
    CountryPrefixCode(
      name: "Mauritania",
      code: "MR",
      dialCode: "+222",
      flag: "🇲🇷",
    ),
    CountryPrefixCode(
      name: "Mauritius",
      code: "MU",
      dialCode: "+230",
      flag: "🇲🇺",
    ),
    CountryPrefixCode(
      name: "Mayotte",
      code: "YT",
      dialCode: "+262",
      flag: "🇾🇹",
    ),
    CountryPrefixCode(
      name: "Mexico",
      code: "MX",
      dialCode: "+52",
      flag: "🇲🇽",
    ),
    CountryPrefixCode(
      name: "Micronesia (Federated States)",
      code: "FM",
      dialCode: "+691",
      flag: "🇫🇲",
    ),
    CountryPrefixCode(
      name: "Moldova",
      code: "MD",
      dialCode: "+373",
      flag: "🇲🇩",
    ),
    CountryPrefixCode(
      name: "Monaco",
      code: "MC",
      dialCode: "+377",
      flag: "🇲🇨",
    ),
    CountryPrefixCode(
      name: "Mongolia",
      code: "MN",
      dialCode: "+976",
      flag: "🇲🇳",
    ),
    CountryPrefixCode(
      name: "Montenegro",
      code: "ME",
      dialCode: "+382",
      flag: "🇲🇪",
    ),
    CountryPrefixCode(
      name: "Montserrat",
      code: "MS",
      dialCode: "+1-664",
      flag: "🇲🇸",
    ),
    CountryPrefixCode(
      name: "Morocco",
      code: "MA",
      dialCode: "+212",
      flag: "🇲🇦",
    ),
    CountryPrefixCode(
      name: "Mozambique",
      code: "MZ",
      dialCode: "+258",
      flag: "🇲🇿",
    ),
    CountryPrefixCode(
      name: "Myanmar",
      code: "MM",
      dialCode: "+95",
      flag: "🇲🇲",
    ),
    CountryPrefixCode(
      name: "Namibia",
      code: "NA",
      dialCode: "+264",
      flag: "🇳🇦",
    ),
    CountryPrefixCode(
      name: "Nauru",
      code: "NR",
      dialCode: "+674",
      flag: "🇳🇷",
    ),
    CountryPrefixCode(
      name: "Nepal",
      code: "NP",
      dialCode: "+977",
      flag: "🇳🇵",
    ),
    CountryPrefixCode(
      name: "Netherlands",
      code: "NL",
      dialCode: "+31",
      flag: "🇳🇱",
    ),
    CountryPrefixCode(
      name: "New Caledonia",
      code: "NC",
      dialCode: "+687",
      flag: "🇳🇨",
    ),
    CountryPrefixCode(
      name: "New Zealand",
      code: "NZ",
      dialCode: "+64",
      flag: "🇳🇿",
    ),
    CountryPrefixCode(
      name: "Nicaragua",
      code: "NI",
      dialCode: "+505",
      flag: "🇳🇮",
    ),
    CountryPrefixCode(
      name: "Niger",
      code: "NE",
      dialCode: "+227",
      flag: "🇳🇪",
    ),
    CountryPrefixCode(
      name: "Nigeria",
      code: "NG",
      dialCode: "+234",
      flag: "🇳🇬",
    ),
    CountryPrefixCode(name: "Niue", code: "NU", dialCode: "+683", flag: "🇳🇺"),
    CountryPrefixCode(
      name: "Norfolk Island",
      code: "NF",
      dialCode: "+672",
      flag: "🇳🇫",
    ),
    CountryPrefixCode(
      name: "Northern Mariana Islands",
      code: "MP",
      dialCode: "+1-670",
      flag: "🇲🇵",
    ),
    CountryPrefixCode(
      name: "Norway",
      code: "NO",
      dialCode: "+47",
      flag: "🇳🇴",
    ),
    CountryPrefixCode(name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲"),
    CountryPrefixCode(
      name: "Pakistan",
      code: "PK",
      dialCode: "+92",
      flag: "🇵🇰",
    ),
    CountryPrefixCode(
      name: "Palau",
      code: "PW",
      dialCode: "+680",
      flag: "🇵🇼",
    ),
    CountryPrefixCode(
      name: "Palestine, State of",
      code: "PS",
      dialCode: "+970",
      flag: "🇵🇸",
    ),
    CountryPrefixCode(
      name: "Panama",
      code: "PA",
      dialCode: "+507",
      flag: "🇵🇦",
    ),
    CountryPrefixCode(
      name: "Papua New Guinea",
      code: "PG",
      dialCode: "+675",
      flag: "🇵🇬",
    ),
    CountryPrefixCode(
      name: "Paraguay",
      code: "PY",
      dialCode: "+595",
      flag: "🇵🇾",
    ),
    CountryPrefixCode(name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪"),
    CountryPrefixCode(
      name: "Philippines",
      code: "PH",
      dialCode: "+63",
      flag: "🇵🇭",
    ),
    CountryPrefixCode(
      name: "Pitcairn",
      code: "PN",
      dialCode: "+64",
      flag: "🇵🇳",
    ),
    CountryPrefixCode(
      name: "Poland",
      code: "PL",
      dialCode: "+48",
      flag: "🇵🇱",
    ),
    CountryPrefixCode(
      name: "Portugal",
      code: "PT",
      dialCode: "+351",
      flag: "🇵🇹",
    ),
    CountryPrefixCode(
      name: "Puerto Rico",
      code: "PR",
      dialCode: "+1-787",
      flag: "🇵🇷",
    ),
    CountryPrefixCode(
      name: "Qatar",
      code: "QA",
      dialCode: "+974",
      flag: "🇶🇦",
    ),
    CountryPrefixCode(
      name: "Réunion",
      code: "RE",
      dialCode: "+262",
      flag: "🇷🇪",
    ),
    CountryPrefixCode(
      name: "Romania",
      code: "RO",
      dialCode: "+40",
      flag: "🇷🇴",
    ),
    CountryPrefixCode(name: "Russia", code: "RU", dialCode: "+7", flag: "🇷🇺"),
    CountryPrefixCode(
      name: "Rwanda",
      code: "RW",
      dialCode: "+250",
      flag: "🇷🇼",
    ),
    CountryPrefixCode(
      name: "Saint Barthélemy",
      code: "BL",
      dialCode: "+590",
      flag: "🇧🇱",
    ),
    CountryPrefixCode(
      name: "Saint Helena, Ascension and Tristan da Cunha",
      code: "SH",
      dialCode: "+290",
      flag: "🇸🇭",
    ),
    CountryPrefixCode(
      name: "Saint Kitts and Nevis",
      code: "KN",
      dialCode: "+1-869",
      flag: "🇰🇳",
    ),
    CountryPrefixCode(
      name: "Saint Lucia",
      code: "LC",
      dialCode: "+1-758",
      flag: "🇱🇨",
    ),
    CountryPrefixCode(
      name: "Saint Martin (French part)",
      code: "MF",
      dialCode: "+590",
      flag: "🇲🇫",
    ),
    CountryPrefixCode(
      name: "Saint Pierre and Miquelon",
      code: "PM",
      dialCode: "+508",
      flag: "🇵🇲",
    ),
    CountryPrefixCode(
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      dialCode: "+1-784",
      flag: "🇻🇨",
    ),
    CountryPrefixCode(
      name: "Samoa",
      code: "WS",
      dialCode: "+685",
      flag: "🇼🇸",
    ),
    CountryPrefixCode(
      name: "San Marino",
      code: "SM",
      dialCode: "+378",
      flag: "🇸🇲",
    ),
    CountryPrefixCode(
      name: "Sao Tome and Principe",
      code: "ST",
      dialCode: "+239",
      flag: "🇸🇹",
    ),
    CountryPrefixCode(
      name: "Saudi Arabia",
      code: "SA",
      dialCode: "+966",
      flag: "🇸🇦",
    ),
    CountryPrefixCode(
      name: "Senegal",
      code: "SN",
      dialCode: "+221",
      flag: "🇸🇳",
    ),
    CountryPrefixCode(
      name: "Serbia",
      code: "RS",
      dialCode: "+381",
      flag: "🇷🇸",
    ),
    CountryPrefixCode(
      name: "Seychelles",
      code: "SC",
      dialCode: "+248",
      flag: "🇸🇨",
    ),
    CountryPrefixCode(
      name: "Sierra Leone",
      code: "SL",
      dialCode: "+232",
      flag: "🇸🇱",
    ),
    CountryPrefixCode(
      name: "Sint Maarten (Dutch part)",
      code: "SX",
      dialCode: "+1-721",
      flag: "🇸🇽",
    ),
    CountryPrefixCode(
      name: "Slovakia",
      code: "SK",
      dialCode: "+421",
      flag: "🇸🇰",
    ),
    CountryPrefixCode(
      name: "Slovenia",
      code: "SI",
      dialCode: "+386",
      flag: "🇸🇮",
    ),
    CountryPrefixCode(
      name: "Solomon Islands",
      code: "SB",
      dialCode: "+677",
      flag: "🇸🇧",
    ),
    CountryPrefixCode(
      name: "Somalia",
      code: "SO",
      dialCode: "+252",
      flag: "🇸🇴",
    ),
    CountryPrefixCode(
      name: "South Africa",
      code: "ZA",
      dialCode: "+27",
      flag: "🇿🇦",
    ),
    CountryPrefixCode(
      name: "South Georgia and the South Sandwich Islands",
      code: "GS",
      dialCode: "+500",
      flag: "🇬🇸",
    ),
    CountryPrefixCode(
      name: "South Sudan",
      code: "SS",
      dialCode: "+211",
      flag: "🇸🇸",
    ),
    CountryPrefixCode(name: "Spain", code: "ES", dialCode: "+34", flag: "🇪🇸"),
    CountryPrefixCode(
      name: "Sri Lanka",
      code: "LK",
      dialCode: "+94",
      flag: "🇱🇰",
    ),
    CountryPrefixCode(
      name: "Sudan",
      code: "SD",
      dialCode: "+249",
      flag: "🇸🇩",
    ),
    CountryPrefixCode(
      name: "Suriname",
      code: "SR",
      dialCode: "+597",
      flag: "🇸🇷",
    ),
    CountryPrefixCode(
      name: "Svalbard and Jan Mayen",
      code: "SJ",
      dialCode: "+47",
      flag: "🇸🇯",
    ),
    CountryPrefixCode(
      name: "Sweden",
      code: "SE",
      dialCode: "+46",
      flag: "🇸🇪",
    ),
    CountryPrefixCode(
      name: "Switzerland",
      code: "CH",
      dialCode: "+41",
      flag: "🇨🇭",
    ),
    CountryPrefixCode(
      name: "Syrian Arab Republic",
      code: "SY",
      dialCode: "+963",
      flag: "🇸🇾",
    ),
    CountryPrefixCode(
      name: "Taiwan",
      code: "TW",
      dialCode: "+886",
      flag: "🇹🇼",
    ),
    CountryPrefixCode(
      name: "Tajikistan",
      code: "TJ",
      dialCode: "+992",
      flag: "🇹🇯",
    ),
    CountryPrefixCode(
      name: "Tanzania, United Republic of",
      code: "TZ",
      dialCode: "+255",
      flag: "🇹🇿",
    ),

    CountryPrefixCode(
      name: "Timor-Leste",
      code: "TL",
      dialCode: "+670",
      flag: "🇹🇱",
    ),
    CountryPrefixCode(name: "Togo", code: "TG", dialCode: "+228", flag: "🇹🇬"),
    CountryPrefixCode(
      name: "Tokelau",
      code: "TK",
      dialCode: "+690",
      flag: "🇹🇰",
    ),
    CountryPrefixCode(
      name: "Tonga",
      code: "TO",
      dialCode: "+676",
      flag: "🇹🇴",
    ),
    CountryPrefixCode(
      name: "Trinidad and Tobago",
      code: "TT",
      dialCode: "+1-868",
      flag: "🇹🇹",
    ),
    CountryPrefixCode(
      name: "Tunisia",
      code: "TN",
      dialCode: "+216",
      flag: "🇹🇳",
    ),
    CountryPrefixCode(
      name: "Turkey",
      code: "TR",
      dialCode: "+90",
      flag: "🇹🇷",
    ),
    CountryPrefixCode(
      name: "Turkmenistan",
      code: "TM",
      dialCode: "+993",
      flag: "🇹🇲",
    ),
    CountryPrefixCode(
      name: "Turks and Caicos Islands",
      code: "TC",
      dialCode: "+1-649",
      flag: "🇹🇨",
    ),
    CountryPrefixCode(
      name: "Tuvalu",
      code: "TV",
      dialCode: "+688",
      flag: "🇹🇻",
    ),
    CountryPrefixCode(
      name: "Uganda",
      code: "UG",
      dialCode: "+256",
      flag: "🇺🇬",
    ),
    CountryPrefixCode(
      name: "Ukraine",
      code: "UA",
      dialCode: "+380",
      flag: "🇺🇦",
    ),
    CountryPrefixCode(
      name: "United Arab Emirates",
      code: "AE",
      dialCode: "+971",
      flag: "🇦🇪",
    ),
    CountryPrefixCode(
      name: "United Kingdom",
      code: "GB",
      dialCode: "+44",
      flag: "🇬🇧",
    ),
    CountryPrefixCode(
      name: "United States",
      code: "US",
      dialCode: "+1",
      flag: "🇺🇸",
    ),
    CountryPrefixCode(
      name: "United States Minor Outlying Islands",
      code: "UM",
      dialCode: "+1-808",
      flag: "🇺🇲",
    ),
    CountryPrefixCode(
      name: "Uruguay",
      code: "UY",
      dialCode: "+598",
      flag: "🇺🇾",
    ),
    CountryPrefixCode(
      name: "Uzbekistan",
      code: "UZ",
      dialCode: "+998",
      flag: "🇺🇿",
    ),
    CountryPrefixCode(
      name: "Vanuatu",
      code: "VU",
      dialCode: "+678",
      flag: "🇻🇺",
    ),
    CountryPrefixCode(
      name: "Venezuela (Bolivarian Republic)",
      code: "VE",
      dialCode: "+58",
      flag: "🇻🇪",
    ),
    CountryPrefixCode(
      name: "Viet Nam",
      code: "VN",
      dialCode: "+84",
      flag: "🇻🇳",
    ),
    CountryPrefixCode(
      name: "Virgin Islands (British)",
      code: "VG",
      dialCode: "+1-284",
      flag: "🇻🇬",
    ),
    CountryPrefixCode(
      name: "Virgin Islands (U.S.)",
      code: "VI",
      dialCode: "+1-340",
      flag: "🇻🇮",
    ),
    CountryPrefixCode(
      name: "Wallis and Futuna",
      code: "WF",
      dialCode: "+681",
      flag: "🇼🇫",
    ),
    CountryPrefixCode(
      name: "Western Sahara",
      code: "EH",
      dialCode: "+212",
      flag: "🇪🇭",
    ),
    CountryPrefixCode(
      name: "Yemen",
      code: "YE",
      dialCode: "+967",
      flag: "🇾🇪",
    ),
    CountryPrefixCode(
      name: "Zambia",
      code: "ZM",
      dialCode: "+260",
      flag: "🇿🇲",
    ),
    CountryPrefixCode(
      name: "Zimbabwe",
      code: "ZW",
      dialCode: "+263",
      flag: "🇿🇼",
    ),
  ];

}

